[package]
name = "skyline-web"
version = "0.1.0"
authors = ["Raytwo <raytwost@gmail.com>"]
edition = "2018"

[dependencies]
skyline = "0.2.1"
nnsdk = { git = "https://github.com/ultimate-research/nnsdk-rs" }
ramhorns = "0.9.4"

# web session json
serde = { version = "1", optional = true }
serde_json = { version = "1", optional = true }

[features]
default = ["json"]
json = ["serde", "serde_json"]
